In [178]:
import pandas as pd

In [179]:
#df=dataframe
df = pd.read_csv('2.csv')
#other location work? need to test

In [180]:
df

Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
1     MainBranch  Which of the following options best describes ...
2       Hobbyist                            Do you code as a hobby?
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[85 rows x 2 columns]

In [181]:
df.axes
# A DataFrame object has two axes: “axis 0” and “axis 1”. “axis 0” represents rows and “axis 1” represents columns. 
# Now it’s clear that Series and DataFrame share the same direction for “axis 0” – it goes along rows direction.
# Our DataFrame object has 0, 1, 2, 3, 4, .....84 indexes along the “axis 0”, and additionally, 
# it has “axis 1” indexes which are: 'Column’ and ‘QuestionText’.
# below, step=1 means the difference between each row is 1

[RangeIndex(start=0, stop=85, step=1),
 Index(['Column', 'QuestionText'], dtype='object')]

In [5]:
#"data analysis with pandas" to study more in youtube. 
#corey schefar

In [6]:
df['Column'].axes

[RangeIndex(start=0, stop=85, step=1)]

In [7]:
df['QuestionText'].axes

[RangeIndex(start=0, stop=85, step=1)]

In [184]:
# this below code is collected from https://railsware.com/blog/python-for-machine-learning-pandas-axis-explained/#:~:text=A%20DataFrame%20object%20has%20two,it%20goes%20along%20rows%20direction.
srs_a = pd.Series([1,3,6,8,9])
srs_b = pd.Series(['red', 'green', 'blue', 'white', 'black'])

In [183]:
df1 = pd.DataFrame({'a': srs_a, 'b': srs_b})

In [185]:
df1

a      b
0  1    red
1  3  green
2  6   blue
3  8  white
4  9  black

In [187]:
#loc=location
df1.loc[2, 'b']

'blue'

In [188]:
df1.loc[3, 'a']

8

In [189]:
df1.empty

False

In [190]:
# .ndm represent dimension of data, series, dataframe or panel? here df is dataframe (2 dimensional data)
df.ndim 

2

In [192]:
srs_a.ndim # one dimensional data 

1

In [193]:
df.shape

(85, 2)

In [194]:
df.size

170

In [16]:
df['QuestionText'].size

85

In [195]:
df

Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
1     MainBranch  Which of the following options best describes ...
2       Hobbyist                            Do you code as a hobby?
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[85 rows x 2 columns]

In [196]:
df.T
# Reflect the DataFrame over its main diagonal by writing rows as columns and vice-versa. The property T is an accessor to the method transpose().

0   \
Column                                               Respondent   
QuestionText  Randomized respondent ID number (not in order ...   

                                                             1   \
Column                                               MainBranch   
QuestionText  Which of the following options best describes ...   

                                   2   \
Column                       Hobbyist   
QuestionText  Do you code as a hobby?   

                                                       3   \
Column                                        OpenSourcer   
QuestionText  How often do you contribute to open source?   

                                                             4   \
Column                                               OpenSource   
QuestionText  How do you feel about the quality of open sour...   

                                                             5   \
Column                                               Employment   
QuestionText  Which of the following best describes your cur...   

                                                     6   \
Column                                          Country   
QuestionText  In which country do you currently reside?   

                                                             7   \
Column                                                  Student   
QuestionText  Are you currently enrolled in a formal, degree...   

                                                             8   \
Column                                                  EdLevel   
QuestionText  Which of the following best describes the high...   

                                                             9   ...  \
Column                                           UndergradMajor  ...   
QuestionText  What was your main or most important field of ...  ...   

                                                             75  \
Column                                            WelcomeChange   
QuestionText  Compared to last year, how welcome do you feel...   

                                                             76  \
Column                                             SONewContent   
QuestionText  Would you like to see any of the following on ...   

                                                             77  \
Column                                                      Age   
QuestionText  What is your age (in years)? If you prefer not...   

                                                             78  \
Column                                                   Gender   
QuestionText  Which of the following do you currently identi...   

                                           79  \
Column                                  Trans   
QuestionText  Do you identify as transgender?   

                                                             80  \
Column                                                Sexuality   
QuestionText  Which of the following do you currently identi...   

                                                             81  \
Column                                                Ethnicity   
QuestionText  Which of the following do you identify as? Ple...   

                                                             82  \
Column                                               Dependents   
QuestionText  Do you have any dependents (e.g., children, el...   

                                                             83  \
Column                                             SurveyLength   
QuestionText  How do you feel about the length of the survey...   

                                                             84  
Column                                               SurveyEase  
QuestionText  How easy or difficult was this survey to compl...  

[2 rows x 85 columns]

In [197]:
df
# actually transpose method change the row to column and column to row but dataframe is till same, see below

Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
1     MainBranch  Which of the following options best describes ...
2       Hobbyist                            Do you code as a hobby?
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[85 rows x 2 columns]

In [20]:
df.head()
# This function returns the first n rows for the object based on position. It is useful for quickly testing if your object has the right type of data in it.
# by default 5 rows

Column                                       QuestionText
0   Respondent  Randomized respondent ID number (not in order ...
1   MainBranch  Which of the following options best describes ...
2     Hobbyist                            Do you code as a hobby?
3  OpenSourcer        How often do you contribute to open source?
4   OpenSource  How do you feel about the quality of open sour...

In [198]:
df.head(10)

Column                                       QuestionText
0      Respondent  Randomized respondent ID number (not in order ...
1      MainBranch  Which of the following options best describes ...
2        Hobbyist                            Do you code as a hobby?
3     OpenSourcer        How often do you contribute to open source?
4      OpenSource  How do you feel about the quality of open sour...
5      Employment  Which of the following best describes your cur...
6         Country          In which country do you currently reside?
7         Student  Are you currently enrolled in a formal, degree...
8         EdLevel  Which of the following best describes the high...
9  UndergradMajor  What was your main or most important field of ...

In [199]:
df.head(-5)
# For negative values of n, this function returns all rows except the last n rows, equivalent to df[:-n].

Column                                       QuestionText
0      Respondent  Randomized respondent ID number (not in order ...
1      MainBranch  Which of the following options best describes ...
2        Hobbyist                            Do you code as a hobby?
3     OpenSourcer        How often do you contribute to open source?
4      OpenSource  How do you feel about the quality of open sour...
..            ...                                                ...
75  WelcomeChange  Compared to last year, how welcome do you feel...
76   SONewContent  Would you like to see any of the following on ...
77            Age  What is your age (in years)? If you prefer not...
78         Gender  Which of the following do you currently identi...
79          Trans                    Do you identify as transgender?

[80 rows x 2 columns]

In [200]:
df.tail()
# This function returns last n rows from the object based on position. It is useful for quickly verifying data, 
# for example, after sorting or appending rows. by default 5

Column                                       QuestionText
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

In [201]:
df.tail(10)
# any specific numbe rof rows, like last 10 rows

Column                                       QuestionText
75  WelcomeChange  Compared to last year, how welcome do you feel...
76   SONewContent  Would you like to see any of the following on ...
77            Age  What is your age (in years)? If you prefer not...
78         Gender  Which of the following do you currently identi...
79          Trans                    Do you identify as transgender?
80      Sexuality  Which of the following do you currently identi...
81      Ethnicity  Which of the following do you identify as? Ple...
82     Dependents  Do you have any dependents (e.g., children, el...
83   SurveyLength  How do you feel about the length of the survey...
84     SurveyEase  How easy or difficult was this survey to compl...

In [25]:
df.tail(-20)
# For negative values of n, this function returns all rows except the first n rows, equivalent to df[n:].

Column                                       QuestionText
20       MgrWant  Do you want to become a manager yourself in th...
21       JobSeek  Which of the following best describes your cur...
22  LastHireDate  When was the last time that you took a job wit...
23       LastInt  In your most recent successful job interview (...
24      FizzBuzz  Have you ever been asked to solve FizzBuzz in ...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[65 rows x 2 columns]

In [26]:
import numpy as np
# to do numerical analysis
# "pip install numpy" -- to install numpy from terminal or we can use the same way pandas is imported in jupyter

In [27]:
np.random.randint(1, size=10) # when 1, start from 0
# to learn more: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.random.randint(5, size=10) #from 0-4

array([0, 0, 1, 0, 1, 1, 4, 4, 2, 1])

In [202]:
np.random.randint(20, size=10)
# array size is 10, the value range may be present between 0 to 19

array([10,  2, 19, 10,  4,  9,  9,  4,  8,  6])

In [203]:
np.random.randint(0, 20, size=20)
# randomly choose a number from 0 to 19(<20)

array([12,  7, 19,  5,  4, 17, 12,  1,  6, 12, 15, 14, 13, 15,  9,  1,  7,
       10,  7,  8])

In [204]:
np.random.randint(11, 20, size=20)
# randomly choose a number from 11 to 19

array([17, 19, 15, 17, 15, 15, 14, 17, 19, 12, 13, 19, 13, 16, 19, 17, 18,
       14, 17, 16])

In [205]:
np.random.randint(11, 20, size=(5, 3))
# numpy.random.randint(low, high=None, size=None, dtype=int) --- we can use this formula
# randomly choose a number from 11 to 19 and row size 5, and column 3

array([[16, 15, 15],
       [12, 17, 15],
       [18, 18, 12],
       [13, 15, 15],
       [16, 17, 11]])

In [46]:
# don't know why it is not working, need to talk with Sazzad, may be columns work on dataframe
# np.random.randint(11, 20, size=(5, 3)), columns=['a', 'b', 'c']

In [207]:
array1=np.random.randint(11, 20, size=(5, 3))

In [208]:
array1.ndim

2

In [210]:
np.random.randint(1,5)

3

In [211]:
np.random.randint(1, [3, 5, 10])
# Generate a 1 x 3 array with 3 different upper bounds

array([2, 4, 1])

In [212]:
np.random.randint([1, 5, 7], 10)
# Generate a 1 by 3 array with 3 different lower bounds

array([4, 7, 8])

In [45]:
np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)
# Generate a 2 by 4 array using broadcasting with dtype of uint8

array([[ 1,  5,  7,  9],
       [17,  4, 12, 19]], dtype=uint8)

In [213]:
np.random.randint(0, high=10, size=15, dtype=int)
# np.random.randint(low, high=None, size=None, dtype=int)

array([1, 3, 2, 1, 9, 9, 7, 8, 4, 3, 9, 2, 6, 2, 5])

In [214]:
# random_integers similar to randint, only for the closed interval [low, high], and 1 is the lowest value if high is omitted.
# randint Similar to random_integers, only for the half-open interval [low, high], and 0 is the lowest value if high is omitted.
np.random.random_integers(5)

<ipython-input-214-4c2553fa5510>:3: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  np.random.random_integers(5)


2

In [38]:
type(np.random.random_integers(5))

<ipython-input-38-c0a5b60d12f0>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  type(np.random.random_integers(5))


numpy.int64

In [226]:
df200=pd.DataFrame(np.random.randint(11, 20, size=(5, 3)), columns=['a', 'b', 'c'])
# randomly choose a number from 11 to 20 and row size 5, and column 3

In [227]:
df200

a   b   c
0  12  15  18
1  18  16  19
2  15  16  12
3  15  18  19
4  19  13  14

In [228]:
df200['a']

0    12
1    18
2    15
3    15
4    19
Name: a, dtype: int64

In [229]:
df200.count
# what is the difference

<bound method DataFrame.count of     a   b   c
0  12  15  18
1  18  16  19
2  15  16  12
3  15  18  19
4  19  13  14>

In [230]:
df200.count()
#how many data present in a, b or c

a    5
b    5
c    5
dtype: int64

In [231]:
df200.count(axis=1)
# how many data present in 0, 1, 2, 3, 4

0    3
1    3
2    3
3    3
4    3
dtype: int64

In [232]:
df200.count(axis=0)
# df.count()  -- similar of this

a    5
b    5
c    5
dtype: int64

In [233]:
df200.sum()
#it consider axis=0, so it sum up from columns

a    79
b    78
c    82
dtype: int64

In [234]:
df200['a'].sum()
# to sum a specific column

79

In [235]:
df200.sum(1)
#it consider axis=1, so it sum up from rows
# how to sum a specific row?

0    45
1    53
2    43
3    52
4    46
dtype: int64

In [236]:
df200.max()
#it gives us the maximum value of each column

a    19
b    18
c    19
dtype: int64

In [237]:
df200['a'].max()
#it gives us the maximum value of a specific column

19

In [238]:
df200.min()
#it gives us the minimum value of each column

a    12
b    13
c    12
dtype: int64

In [239]:
df200['b'].min()
#it gives us the minimum value of a specific column

13

In [240]:
df200.std()
#it gives us the standard deviation of each column

a    2.774887
b    1.816590
c    3.209361
dtype: float64

In [241]:
df200['c'].std()
#it gives us the standard deviation of a specific column

3.209361307176242

In [242]:
df200.std(1)
#1 from axis=1
#it gives us the standard deviation of each row

0    3.000000
1    1.527525
2    2.081666
3    2.081666
4    3.214550
dtype: float64

In [245]:
#df200[3].std(1)
#how to find std for a specific row

In [249]:
df200.describe()
# a lot of info come regarding columnsdf.

a         b          c
count   5.000000   5.00000   5.000000
mean   15.800000  15.60000  16.400000
std     2.774887   1.81659   3.209361
min    12.000000  13.00000  12.000000
25%    15.000000  15.00000  14.000000
50%    15.000000  16.00000  18.000000
75%    18.000000  16.00000  19.000000
max    19.000000  18.00000  19.000000

In [250]:
df200

a   b   c
0  12  15  18
1  18  16  19
2  15  16  12
3  15  18  19
4  19  13  14

In [251]:
# farenhite to celsius
def convertToCelsius (x):
    c = (x-32)*5/9
    return c

In [252]:
convertToCelsius (89)

31.666666666666668

In [256]:
for i in df200['a']:
    print (i)

12
18
15
15
19


In [257]:
for i in df200 ['b']:
    print (i)

15
16
16
18
13


In [261]:
for i in df200 ['a']:
    print (convertToCelsius (i))

-11.11111111111111
-7.777777777777778
-9.444444444444445
-9.444444444444445
-7.222222222222222


In [273]:
df200
# still same

a   b   c
0  30  15  18
1  -7  16  19
2  15  16  12
3  15  18  19
4  19  13  14

In [263]:
df200['a'][0]
# value present in index 0 of colum a

12

In [264]:
df200['a'][0]=87
# change it to 87 from 12, see below, but how could we change all?

In [272]:
df200

a   b   c
0  30  15  18
1  -7  16  19
2  15  16  12
3  15  18  19
4  19  13  14

In [267]:
# c=0
# for i in df200 ['a']:
#     print (convertToCelsius (i)) # so it only change in one place and don't integrate in framework

30.555555555555557
-7.777777777777778
-9.444444444444445
-9.444444444444445
-7.222222222222222


In [282]:
c=0
for i in df200 ['a']:
    print (convertToCelsius (i))
    df200['a'][c]=convertToCelsius (i)
    c=+4
    # this have some problem, data is always changing, may be because of above code

-1.1111111111111112
-21.666666666666668
-9.444444444444445
-9.444444444444445
-22.77777777777778


In [283]:
df200

a           b   c
0  -1  2562890625  18
1  -7         169  19
2  15         169  12
3  15         169  19
4 -22          13  14

In [284]:
def getSquare(x):
    return x*x

In [285]:
getSquare(6)

36

In [291]:
d=0
for i in df200 ['b']:
    #print (convertToCelsius (i))
    df200['b'][d]= getSquare (i)
    d=+4

OverflowError: Python int too large to convert to C long

In [288]:
df200
#they become sqaure

a                    b   c
0  -1  6568408355712890625  18
1  -7                  169  19
2  15                  169  12
3  15                  169  19
4 -22            815730721  14

In [292]:
a=lambda x: x*x
# lambda function is defined

In [293]:
a(4)

16

In [294]:
df200['c']=df200['c'].apply(lambda x: x*x) 
# if we don't assign as df['a'] it will not be changed
# lambda function is defined

In [295]:
df200

a                    b    c
0  -1  6568408355712890625  324
1  -7                  169  361
2  15                  169  144
3  15                  169  361
4 -22            815730721  196

In [296]:
df200['c']=df['c'].apply(lambda x: getSquare(x)) 
# we can also use this instead of lambda, but for lambda need less code

In [298]:
df200

a                    b    c
0  -1  6568408355712890625  361
1  -7                  169  169
2  15                  169  196
3  15                  169  169
4 -22            815730721  121

In [299]:
import time

In [300]:
df_new=pd.DataFrame(np.random.randint(11, 20, size=(1000, 3)), columns=['a', 'b', 'c'])

In [301]:
df_new

a   b   c
0    17  16  15
1    12  12  11
2    14  12  19
3    14  14  14
4    15  14  15
..   ..  ..  ..
995  13  16  15
996  19  17  11
997  14  15  12
998  18  13  19
999  12  16  15

[1000 rows x 3 columns]

In [302]:
#measuring time of execution without lembda
start = time.time()
c=0
for i in df_new ['a']:
    #print (convertToCelsius (i))
    df_new['a'][c]= getSquare (i)
    c=+1
end=time.time()
end-start

0.06287884712219238

In [303]:
#measuring time of execution with lembda, it takes less time than regular
start = time.time()
df['a']=df['a'].apply(lambda x: getSquare(x)) # if we use this will take lesser time -- df['a']=df['a'].apply(lambda x: x*x) 
end=time.time()
end-start

0.0007309913635253906

In [304]:
# How to create a blank data frame
df5 = pd.DataFrame()
# class pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)[source]
# Two-dimensional, size-mutable, potentially heterogeneous tabular data.
# Data structure also contains labeled axes (rows and columns). Arithmetic operations align on both row and column
# labels. Can be thought of as a dict-like container for Series objects. The primary pandas data structure.
# to read more: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

In [305]:
df5

Empty DataFrame
Columns: []
Index: []

In [306]:
df5.empty

True

In [307]:
# Same as above, will show empty
df6 = pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)


In [308]:
df6


Empty DataFrame
Columns: []
Index: []

In [309]:
df6.empty

True

In [310]:
import os
# to import operating system

In [311]:
os.getcwd()
# to see the location of this file

'/Users/mohammadsharkar'

In [312]:
# make a dataframe of 5000 rows and 4 column
# first column change to square
# second columns - farenhite to celsius
# third column - increase by 100
# 4th column - replace by men column of the whole 4 column

In [313]:
df_hw=pd.DataFrame(np.random.randint(11, 20, size=(5000, 4)), columns=['Changed to square', 'Farenhite to celsius', 'Increased by 100', 'Convert to Mean value'])

In [164]:
df_hw

Changed to square  Farenhite to celsius  Increased by 100  \
0                    14                    16                13   
1                    18                    16                18   
2                    12                    11                11   
3                    15                    11                19   
4                    16                    12                19   
...                 ...                   ...               ...   
4995                 16                    15                19   
4996                 17                    14                16   
4997                 16                    11                11   
4998                 15                    11                12   
4999                 11                    14                18   

      Convert to Mean value  
0                        18  
1                        14  
2                        19  
3                        13  
4                        14  
...                     ...  
4995                     19  
4996                     17  
4997                     19  
4998                     14  
4999                     17  

[5000 rows x 4 columns]

In [314]:
df_hw['Changed to square']=df_hw['Changed to square'].apply(lambda x: x*x)

In [315]:
df_hw

Changed to square  Farenhite to celsius  Increased by 100  \
0                   144                    17                17   
1                   361                    14                15   
2                   144                    14                13   
3                   256                    16                17   
4                   256                    13                15   
...                 ...                   ...               ...   
4995                256                    13                14   
4996                169                    13                19   
4997                324                    16                13   
4998                289                    14                18   
4999                225                    19                17   

      Convert to Mean value  
0                        16  
1                        12  
2                        13  
3                        18  
4                        15  
...                     ...  
4995                     14  
4996                     13  
4997                     13  
4998                     14  
4999                     15  

[5000 rows x 4 columns]

In [316]:
df_hw['Farenhite to celsius']=df_hw['Farenhite to celsius'].apply(lambda y: (y-32)*5/9)

In [317]:
df_hw

Changed to square  Farenhite to celsius  Increased by 100  \
0                   144             -8.333333                17   
1                   361            -10.000000                15   
2                   144            -10.000000                13   
3                   256             -8.888889                17   
4                   256            -10.555556                15   
...                 ...                   ...               ...   
4995                256            -10.555556                14   
4996                169            -10.555556                19   
4997                324             -8.888889                13   
4998                289            -10.000000                18   
4999                225             -7.222222                17   

      Convert to Mean value  
0                        16  
1                        12  
2                        13  
3                        18  
4                        15  
...                     ...  
4995                     14  
4996                     13  
4997                     13  
4998                     14  
4999                     15  

[5000 rows x 4 columns]

In [318]:
df_hw['Increased by 100']=df_hw['Increased by 100'].apply(lambda z: z+100)

In [319]:
df_hw

Changed to square  Farenhite to celsius  Increased by 100  \
0                   144             -8.333333               117   
1                   361            -10.000000               115   
2                   144            -10.000000               113   
3                   256             -8.888889               117   
4                   256            -10.555556               115   
...                 ...                   ...               ...   
4995                256            -10.555556               114   
4996                169            -10.555556               119   
4997                324             -8.888889               113   
4998                289            -10.000000               118   
4999                225             -7.222222               117   

      Convert to Mean value  
0                        16  
1                        12  
2                        13  
3                        18  
4                        15  
...                     ...  
4995                     14  
4996                     13  
4997                     13  
4998                     14  
4999                     15  

[5000 rows x 4 columns]

In [320]:
df_hw.describe()

Changed to square  Farenhite to celsius  Increased by 100  \
count        5000.000000           5000.000000       5000.000000   
mean          230.182400             -9.456444        114.971200   
std            77.724116              1.447485          2.600716   
min           121.000000            -11.666667        111.000000   
25%           169.000000            -10.555556        113.000000   
50%           225.000000             -9.444444        115.000000   
75%           289.000000             -8.333333        117.000000   
max           361.000000             -7.222222        119.000000   

       Convert to Mean value  
count            5000.000000  
mean               14.990800  
std                 2.593465  
min                11.000000  
25%                13.000000  
50%                15.000000  
75%                17.000000  
max                19.000000

In [321]:
df_hw['Convert to Mean value']=df_hw['Convert to Mean value'].mean()

In [322]:
df_hw

Changed to square  Farenhite to celsius  Increased by 100  \
0                   144             -8.333333               117   
1                   361            -10.000000               115   
2                   144            -10.000000               113   
3                   256             -8.888889               117   
4                   256            -10.555556               115   
...                 ...                   ...               ...   
4995                256            -10.555556               114   
4996                169            -10.555556               119   
4997                324             -8.888889               113   
4998                289            -10.000000               118   
4999                225             -7.222222               117   

      Convert to Mean value  
0                   14.9908  
1                   14.9908  
2                   14.9908  
3                   14.9908  
4                   14.9908  
...                     ...  
4995                14.9908  
4996                14.9908  
4997                14.9908  
4998                14.9908  
4999                14.9908  

[5000 rows x 4 columns]

In [324]:
start = time.time()
df_hw
end=time.time()
end-start

9.202957153320312e-05